import type { SeedEngine } from "./engine";
import { FEATURES } from "./features";
import type { Dim, EngineInfo } from "./protocol";

export interface MapPoint {
	x: number;
	z: number;
}

export interface Selection extends MapPoint {
	kind: "feature" | "stronghold" | "spawn" | "point";
	label: string;
	biome?: string;
}

export interface Hover extends MapPoint {
	biome?: string;
}

/** everything the renderer needs from the page; replaced as a whole on every change */
export interface MapState {
	engine: SeedEngine;
	info: EngineInfo;
	/** changes whenever the seed or version changes, drops everything that was cached */
	epoch: number;
	dim: Dim;
	/** ids of the structure features to show */
	features: Set<string>;
	showSlime: boolean;
	showGrid: boolean;
	spawn: MapPoint | null;
	/** flat x, z pairs */
	strongholds: Int32Array | null;
	/** highlighted spot, e.g. the result of the biome finder */
	pin: MapPoint | null;
}

export interface MapCallbacks {
	onHover: (hover: Hover | null) => void;
	onSelect: (selection: Selection) => void;
}

const TILE_CELLS = 64;
const SCALES = [1, 4, 16, 64, 256];
const MIN_BPP = 0.25;
const MAX_BPP = 128;
const MAX_TILES = 400;

interface Tile {
	bitmap: ImageBitmap;
	ids: Int32Array;
}

interface Area {
	x0: number;
	z0: number;
	x1: number;
	z1: number;
}

interface Hit extends Selection {
	sx: number;
	sy: number;
}

/** biome cells never get bigger than this many pixels, so the map stays sharp when zooming in */
function pickScale(blocksPerPixel: number, dim: Dim) {
	let best = 1;
	for (const scale of SCALES) {
		// cubiomes only has the 1:256 scale for the overworld
		if (dim !== 0 && scale > 64) continue;
		if (scale / blocksPerPixel <= 4) best = scale;
	}
	return best;
}

const clamp = (value: number, min: number, max: number) => Math.min(Math.max(value, min), max);

/**
 * Draws the world map on a canvas: biome tiles generated by the engine, structure markers, slime
 * chunks and a chunk grid. Handles dragging, wheel zoom, hover and clicks itself.
 */
export class MapRenderer {
	private view = { x: 0, z: 0, bpp: 4 };
	private size = { w: 1, h: 1, ratio: 1 };
	private tiles = new Map<string, Tile | "pending">();
	private features = new Map<string, Area & { points: Int32Array }>();
	private fetching = new Set<string>();
	private slime: { cx: number; cz: number; w: number; h: number; data: Uint8Array } | null = null;
	private slimeFetching = false;
	private hits: Hit[] = [];
	private frame = 0;
	private overlayTimer = 0;
	private observer: ResizeObserver;
	private cleanup: (() => void)[] = [];

	constructor(
		private canvas: HTMLCanvasElement,
		private state: MapState,
		private callbacks: MapCallbacks,
	) {
		this.observer = new ResizeObserver(() => this.resize());
		this.observer.observe(canvas);
		this.resize();
		this.listen();
	}

	/** new props from the page; a new epoch or dimension starts from scratch */
	update(state: MapState, callbacks: MapCallbacks) {
		const reset = state.epoch !== this.state.epoch || state.dim !== this.state.dim;
		this.state = state;
		this.callbacks = callbacks;
		if (reset) {
			this.tiles.clear();
			this.features.clear();
			this.fetching.clear();
			this.slime = null;
		}
		this.requestDraw();
		this.scheduleOverlays();
	}

	goTo(x: number, z: number, blocksPerPixel?: number) {
		this.view.x = x;
		this.view.z = z;
		if (blocksPerPixel) this.view.bpp = clamp(blocksPerPixel, MIN_BPP, MAX_BPP);
		this.requestDraw();
		this.scheduleOverlays();
	}

	zoom(direction: 1 | -1) {
		this.view.bpp = clamp(this.view.bpp * (direction > 0 ? 0.5 : 2), MIN_BPP, MAX_BPP);
		this.requestDraw();
		this.scheduleOverlays();
	}

	center(): MapPoint {
		return { x: Math.round(this.view.x), z: Math.round(this.view.z) };
	}

	destroy() {
		this.observer.disconnect();
		cancelAnimationFrame(this.frame);
		window.clearTimeout(this.overlayTimer);
		for (const remove of this.cleanup) remove();
	}

	private resize() {
		const ratio = Math.max(window.devicePixelRatio, 1);
		const w = this.canvas.clientWidth;
		const h = this.canvas.clientHeight;
		this.size = { w, h, ratio };
		this.canvas.width = Math.round(w * ratio);
		this.canvas.height = Math.round(h * ratio);
		this.requestDraw();
		this.scheduleOverlays();
	}

	private requestDraw() {
		if (!this.frame) {
			this.frame = requestAnimationFrame(() => {
				this.frame = 0;
				this.draw();
			});
		}
	}

	private scheduleOverlays() {
		window.clearTimeout(this.overlayTimer);
		this.overlayTimer = window.setTimeout(() => this.fetchOverlays(), 120);
	}

	private visibleArea(): Area {
		const { x, z, bpp } = this.view;
		const { w, h } = this.size;
		return {
			x0: x - (w / 2) * bpp,
			z0: z - (h / 2) * bpp,
			x1: x + (w / 2) * bpp,
			z1: z + (h / 2) * bpp,
		};
	}

	private requestTile(key: string, dim: Dim, scale: number, tx: number, tz: number) {
		const { engine, info, epoch } = this.state;
		this.tiles.set(key, "pending");
		engine
			.tile({ dim, scale, x: tx * TILE_CELLS, z: tz * TILE_CELLS, size: TILE_CELLS })
			.then(async (ids) => {
				const pixels = new Uint8ClampedArray(TILE_CELLS * TILE_CELLS * 4);
				for (let i = 0; i < ids.length; i++) {
					const id = ids[i];
					const known = id >= 0 && id < 256;
					pixels[i * 4] = known ? info.colors[id * 3] : 40;
					pixels[i * 4 + 1] = known ? info.colors[id * 3 + 1] : 40;
					pixels[i * 4 + 2] = known ? info.colors[id * 3 + 2] : 40;
					pixels[i * 4 + 3] = 255;
				}
				const bitmap = await createImageBitmap(new ImageData(pixels, TILE_CELLS, TILE_CELLS));
				// a tile of an older world is not needed anymore
				if (this.state.epoch !== epoch) return;
				if (this.tiles.size >= MAX_TILES) {
					const oldest = this.tiles.keys().next().value;
					if (oldest !== undefined) this.tiles.delete(oldest);
				}
				this.tiles.set(key, { bitmap, ids });
				this.requestDraw();
			})
			.catch(() => this.tiles.delete(key));
	}

	private draw() {
		const { dim, features, showSlime, showGrid, spawn, strongholds, pin, epoch, info } = this.state;
		const { w, h, ratio } = this.size;
		const ctx = this.canvas.getContext("2d") as CanvasRenderingContext2D;
		ctx.setTransform(ratio, 0, 0, ratio, 0, 0);
		ctx.imageSmoothingEnabled = false;
		ctx.fillStyle = "#101010";
		ctx.fillRect(0, 0, w, h);

		const { x: cx, z: cz, bpp } = this.view;
		const toScreenX = (x: number) => (x - cx) / bpp + w / 2;
		const toScreenY = (z: number) => (z - cz) / bpp + h / 2;
		const { x0: left, z0: top, x1: right, z1: bottom } = this.visibleArea();

		// biome tiles
		const scale = pickScale(bpp, dim);
		const span = scale * TILE_CELLS;
		const px = span / bpp;
		for (let tz = Math.floor(top / span); tz <= Math.floor(bottom / span); tz++) {
			for (let tx = Math.floor(left / span); tx <= Math.floor(right / span); tx++) {
				const key = `${epoch}:${dim}:${scale}:${tx}:${tz}`;
				const tile = this.tiles.get(key);
				if (tile === undefined) this.requestTile(key, dim, scale, tx, tz);
				else if (tile !== "pending") {
					// one extra pixel hides the seams between tiles
					ctx.drawImage(tile.bitmap, toScreenX(tx * span), toScreenY(tz * span), px + 1, px + 1);
				}
			}
		}

		// slime chunks
		const chunk = 16 / bpp;
		if (showSlime && this.slime && dim === 0) {
			const { cx: sx0, cz: sz0, w: sw, h: sh, data } = this.slime;
			ctx.fillStyle = "rgb(110 220 90 / 0.55)";
			for (let j = 0; j < sh; j++) {
				for (let i = 0; i < sw; i++) {
					if (!data[j * sw + i]) continue;
					ctx.fillRect(
						toScreenX((sx0 + i) * 16),
						toScreenY((sz0 + j) * 16),
						chunk + 0.5,
						chunk + 0.5,
					);
				}
			}
		}

		// chunk grid and the axes
		if (showGrid && bpp <= 1) {
			ctx.strokeStyle = "rgb(255 255 255 / 0.12)";
			ctx.lineWidth = 1;
			ctx.beginPath();
			for (let x = Math.floor(left / 16) * 16; x <= right; x += 16) {
				ctx.moveTo(Math.round(toScreenX(x)) + 0.5, 0);
				ctx.lineTo(Math.round(toScreenX(x)) + 0.5, h);
			}
			for (let z = Math.floor(top / 16) * 16; z <= bottom; z += 16) {
				ctx.moveTo(0, Math.round(toScreenY(z)) + 0.5);
				ctx.lineTo(w, Math.round(toScreenY(z)) + 0.5);
			}
			ctx.stroke();
		}
		ctx.strokeStyle = "rgb(255 255 255 / 0.35)";
		ctx.lineWidth = 1;
		ctx.beginPath();
		ctx.moveTo(Math.round(toScreenX(0)) + 0.5, 0);
		ctx.lineTo(Math.round(toScreenX(0)) + 0.5, h);
		ctx.moveTo(0, Math.round(toScreenY(0)) + 0.5);
		ctx.lineTo(w, Math.round(toScreenY(0)) + 0.5);
		ctx.stroke();

		// markers
		const hits: Hit[] = [];
		const marker = (
			x: number,
			z: number,
			color: string,
			text: string,
			label: string,
			kind: Selection["kind"],
			big = bpp <= 8,
		) => {
			const sx = toScreenX(x);
			const sy = toScreenY(z);
			if (sx < -20 || sy < -20 || sx > w + 20 || sy > h + 20) return;
			const s = big ? 20 : 9;
			ctx.fillStyle = color;
			ctx.strokeStyle = "rgb(0 0 0 / 0.8)";
			ctx.lineWidth = 2;
			ctx.strokeRect(sx - s / 2, sy - s / 2, s, s);
			ctx.fillRect(sx - s / 2, sy - s / 2, s, s);
			if (big) {
				ctx.fillStyle = "#fff";
				ctx.font = "600 10px 'IBM Plex Mono', monospace";
				ctx.textAlign = "center";
				ctx.textBaseline = "middle";
				ctx.fillText(text, sx, sy + 0.5);
			}
			hits.push({ sx, sy, x, z, label, kind });
		};

		for (const feature of FEATURES) {
			if (!features.has(feature.id) || feature.dim !== dim || info.dims[feature.type] !== dim)
				continue;
			const points = this.features.get(feature.id)?.points;
			if (!points) continue;
			for (let i = 0; i < points.length; i += 2) {
				marker(points[i], points[i + 1], feature.color, feature.short, feature.name, "feature");
			}
		}
		if (strongholds && dim === 0) {
			for (let i = 0; i < strongholds.length; i += 2) {
				marker(
					strongholds[i],
					strongholds[i + 1],
					"#7d3ad1",
					"S",
					"Stronghold",
					"stronghold",
					true,
				);
			}
		}
		if (spawn && dim === 0) marker(spawn.x, spawn.z, "#2f9e44", "W", "World spawn", "spawn", true);
		this.hits = hits;

		if (pin) {
			const sx = toScreenX(pin.x);
			const sy = toScreenY(pin.z);
			ctx.strokeStyle = "#fff";
			ctx.lineWidth = 2;
			ctx.beginPath();
			ctx.arc(sx, sy, 14, 0, Math.PI * 2);
			for (const [dx, dy] of [
				[1, 0],
				[-1, 0],
				[0, 1],
				[0, -1],
			]) {
				ctx.moveTo(sx + dx * 8, sy + dy * 8);
				ctx.lineTo(sx + dx * 20, sy + dy * 20);
			}
			ctx.stroke();
		}

		// scale bar
		const nice = [10, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000].reduce((best, n) =>
			Math.abs(n - 100 * bpp) < Math.abs(best - 100 * bpp) ? n : best,
		);
		const barPx = nice / bpp;
		ctx.fillStyle = "rgb(0 0 0 / 0.6)";
		ctx.fillRect(10, h - 30, barPx + 16, 20);
		ctx.fillStyle = "#fff";
		ctx.fillRect(18, h - 14, barPx, 2);
		ctx.font = "11px 'IBM Plex Mono', monospace";
		ctx.textAlign = "left";
		ctx.textBaseline = "alphabetic";
		ctx.fillText(`${nice} blocks`, 18, h - 18);
	}

	/** structures and slime chunks come from the engine for the area around the view */
	private fetchOverlays() {
		const { engine, epoch, dim, features, showSlime, info } = this.state;
		const { bpp } = this.view;
		const visible = this.visibleArea();
		const halfW = (visible.x1 - visible.x0) / 2;
		const halfH = (visible.z1 - visible.z0) / 2;

		for (const feature of FEATURES) {
			if (!features.has(feature.id) || feature.dim !== dim || info.dims[feature.type] !== dim)
				continue;
			const have = this.features.get(feature.id);
			const covered =
				have &&
				have.x0 <= visible.x0 &&
				have.z0 <= visible.z0 &&
				have.x1 >= visible.x1 &&
				have.z1 >= visible.z1;
			if (covered || this.fetching.has(feature.id)) continue;

			// ask for a bit more than what is on screen so small pans need no new request
			const area: Area = {
				x0: Math.floor(visible.x0 - halfW / 2),
				z0: Math.floor(visible.z0 - halfH / 2),
				x1: Math.ceil(visible.x1 + halfW / 2),
				z1: Math.ceil(visible.z1 + halfH / 2),
			};
			this.fetching.add(feature.id);
			engine
				.structures({ type: feature.type, ...area, max: 800 })
				.then((points) => {
					if (this.state.epoch === epoch) this.features.set(feature.id, { ...area, points });
				})
				.catch(() => {})
				.finally(() => {
					this.fetching.delete(feature.id);
					this.requestDraw();
				});
		}

		if (showSlime && dim === 0 && bpp <= 8 && !this.slimeFetching) {
			const cx = Math.floor(visible.x0 / 16) - 1;
			const cz = Math.floor(visible.z0 / 16) - 1;
			const w = Math.ceil(visible.x1 / 16) - cx + 2;
			const h = Math.ceil(visible.z1 / 16) - cz + 2;
			const have = this.slime;
			const covered =
				have &&
				have.cx <= cx &&
				have.cz <= cz &&
				have.cx + have.w >= cx + w &&
				have.cz + have.h >= cz + h;
			if (!covered && w * h <= 160_000) {
				this.slimeFetching = true;
				engine
					.slime({ cx, cz, w, h })
					.then((data) => {
						if (this.state.epoch === epoch) this.slime = { cx, cz, w, h, data };
					})
					.catch(() => {})
					.finally(() => {
						this.slimeFetching = false;
						this.requestDraw();
					});
			}
		}
	}

	private toWorld(event: { clientX: number; clientY: number }) {
		const rect = this.canvas.getBoundingClientRect();
		const { x, z, bpp } = this.view;
		return {
			sx: event.clientX - rect.left,
			sy: event.clientY - rect.top,
			x: Math.floor(x + (event.clientX - rect.left - rect.width / 2) * bpp),
			z: Math.floor(z + (event.clientY - rect.top - rect.height / 2) * bpp),
		};
	}

	/** biome name from a tile that is already loaded */
	private biomeAt(x: number, z: number) {
		const { info, epoch, dim } = this.state;
		const scale = pickScale(this.view.bpp, dim);
		const span = scale * TILE_CELLS;
		const tx = Math.floor(x / span);
		const tz = Math.floor(z / span);
		const tile = this.tiles.get(`${epoch}:${dim}:${scale}:${tx}:${tz}`);
		if (!tile || tile === "pending") return undefined;
		const cellX = Math.floor((x - tx * span) / scale);
		const cellZ = Math.floor((z - tz * span) / scale);
		return info.names[tile.ids[cellZ * TILE_CELLS + cellX]];
	}

	private nearestHit(sx: number, sy: number) {
		let best: Hit | null = null;
		let bestDistance = 14;
		for (const hit of this.hits) {
			const distance = Math.hypot(hit.sx - sx, hit.sy - sy);
			if (distance < bestDistance) {
				best = hit;
				bestDistance = distance;
			}
		}
		return best;
	}

	private listen() {
		const canvas = this.canvas;
		let drag: { x: number; y: number; moved: number } | null = null;
		let hoverFrame = 0;

		const onDown = (event: PointerEvent) => {
			drag = { x: event.clientX, y: event.clientY, moved: 0 };
			canvas.setPointerCapture(event.pointerId);
		};
		const onMove = (event: PointerEvent) => {
			if (drag) {
				const dx = event.clientX - drag.x;
				const dy = event.clientY - drag.y;
				drag.x = event.clientX;
				drag.y = event.clientY;
				drag.moved += Math.abs(dx) + Math.abs(dy);
				this.view.x -= dx * this.view.bpp;
				this.view.z -= dy * this.view.bpp;
				this.requestDraw();
				this.scheduleOverlays();
			}
			cancelAnimationFrame(hoverFrame);
			hoverFrame = requestAnimationFrame(() => {
				const p = this.toWorld(event);
				this.callbacks.onHover({ x: p.x, z: p.z, biome: this.biomeAt(p.x, p.z) });
			});
		};
		const onUp = (event: PointerEvent) => {
			const wasClick = drag !== null && drag.moved < 5;
			drag = null;
			if (!wasClick) return;
			const p = this.toWorld(event);
			const hit = this.nearestHit(p.sx, p.sy);
			this.callbacks.onSelect(
				hit
					? {
							kind: hit.kind,
							label: hit.label,
							x: hit.x,
							z: hit.z,
							biome: this.biomeAt(hit.x, hit.z),
						}
					: { kind: "point", label: "Location", x: p.x, z: p.z, biome: this.biomeAt(p.x, p.z) },
			);
		};
		const onLeave = () => this.callbacks.onHover(null);
		const onWheel = (event: WheelEvent) => {
			event.preventDefault();
			const before = this.toWorld(event);
			const next = clamp(this.view.bpp * 2 ** (event.deltaY * 0.0015), MIN_BPP, MAX_BPP);
			this.view.bpp = next;
			// keep the point under the cursor where it is
			const rect = canvas.getBoundingClientRect();
			this.view.x = before.x - (before.sx - rect.width / 2) * next;
			this.view.z = before.z - (before.sy - rect.height / 2) * next;
			this.requestDraw();
			this.scheduleOverlays();
		};

		canvas.addEventListener("pointerdown", onDown);
		canvas.addEventListener("pointermove", onMove);
		canvas.addEventListener("pointerup", onUp);
		canvas.addEventListener("pointerleave", onLeave);
		canvas.addEventListener("wheel", onWheel, { passive: false });
		this.cleanup.push(() => {
			cancelAnimationFrame(hoverFrame);
			canvas.removeEventListener("pointerdown", onDown);
			canvas.removeEventListener("pointermove", onMove);
			canvas.removeEventListener("pointerup", onUp);
			canvas.removeEventListener("pointerleave", onLeave);
			canvas.removeEventListener("wheel", onWheel);
		});
	}
}
