/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Tool3dArmorTrimViewerRouteImport } from './routes/tool/3d-armor-trim-viewer'
import { Route as ToolBannerGeneratorRouteImport } from './routes/tool/banner-generator'
import { Route as ToolBestEnchantmentsRouteImport } from './routes/tool/best-enchantments'
import { Route as ToolCircleGeneratorRouteImport } from './routes/tool/circle-generator'
import { Route as ToolEnchantOrderRouteImport } from './routes/tool/enchant-order'
import { Route as ToolFireworkGeneratorRouteImport } from './routes/tool/firework-generator'
import { Route as ToolItemChecklistRouteImport } from './routes/tool/item-checklist'
import { Route as ToolNetherPortalRouteImport } from './routes/tool/nether-portal'
import { Route as ToolPotionMakerRouteImport } from './routes/tool/potion-maker'
import { Route as ToolSeedMapRouteImport } from './routes/tool/seed-map'
import { Route as ToolShieldGeneratorRouteImport } from './routes/tool/shield-generator'
import { Route as ToolSlimeChunkFinderRouteImport } from './routes/tool/slime-chunk-finder'
import { Route as ToolStackCalculatorRouteImport } from './routes/tool/stack-calculator'
import { Route as ToolVillagerTradingRouteImport } from './routes/tool/villager-trading'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Tool3dArmorTrimViewerRoute = Tool3dArmorTrimViewerRouteImport.update({
  id: '/tool/3d-armor-trim-viewer',
  path: '/tool/3d-armor-trim-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolBannerGeneratorRoute = ToolBannerGeneratorRouteImport.update({
  id: '/tool/banner-generator',
  path: '/tool/banner-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolBestEnchantmentsRoute = ToolBestEnchantmentsRouteImport.update({
  id: '/tool/best-enchantments',
  path: '/tool/best-enchantments',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolCircleGeneratorRoute = ToolCircleGeneratorRouteImport.update({
  id: '/tool/circle-generator',
  path: '/tool/circle-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolEnchantOrderRoute = ToolEnchantOrderRouteImport.update({
  id: '/tool/enchant-order',
  path: '/tool/enchant-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolFireworkGeneratorRoute = ToolFireworkGeneratorRouteImport.update({
  id: '/tool/firework-generator',
  path: '/tool/firework-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolItemChecklistRoute = ToolItemChecklistRouteImport.update({
  id: '/tool/item-checklist',
  path: '/tool/item-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolNetherPortalRoute = ToolNetherPortalRouteImport.update({
  id: '/tool/nether-portal',
  path: '/tool/nether-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolPotionMakerRoute = ToolPotionMakerRouteImport.update({
  id: '/tool/potion-maker',
  path: '/tool/potion-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolSeedMapRoute = ToolSeedMapRouteImport.update({
  id: '/tool/seed-map',
  path: '/tool/seed-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolShieldGeneratorRoute = ToolShieldGeneratorRouteImport.update({
  id: '/tool/shield-generator',
  path: '/tool/shield-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolSlimeChunkFinderRoute = ToolSlimeChunkFinderRouteImport.update({
  id: '/tool/slime-chunk-finder',
  path: '/tool/slime-chunk-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolStackCalculatorRoute = ToolStackCalculatorRouteImport.update({
  id: '/tool/stack-calculator',
  path: '/tool/stack-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolVillagerTradingRoute = ToolVillagerTradingRouteImport.update({
  id: '/tool/villager-trading',
  path: '/tool/villager-trading',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tool/3d-armor-trim-viewer': typeof Tool3dArmorTrimViewerRoute
  '/tool/banner-generator': typeof ToolBannerGeneratorRoute
  '/tool/best-enchantments': typeof ToolBestEnchantmentsRoute
  '/tool/circle-generator': typeof ToolCircleGeneratorRoute
  '/tool/enchant-order': typeof ToolEnchantOrderRoute
  '/tool/firework-generator': typeof ToolFireworkGeneratorRoute
  '/tool/item-checklist': typeof ToolItemChecklistRoute
  '/tool/nether-portal': typeof ToolNetherPortalRoute
  '/tool/potion-maker': typeof ToolPotionMakerRoute
  '/tool/seed-map': typeof ToolSeedMapRoute
  '/tool/shield-generator': typeof ToolShieldGeneratorRoute
  '/tool/slime-chunk-finder': typeof ToolSlimeChunkFinderRoute
  '/tool/stack-calculator': typeof ToolStackCalculatorRoute
  '/tool/villager-trading': typeof ToolVillagerTradingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tool/3d-armor-trim-viewer': typeof Tool3dArmorTrimViewerRoute
  '/tool/banner-generator': typeof ToolBannerGeneratorRoute
  '/tool/best-enchantments': typeof ToolBestEnchantmentsRoute
  '/tool/circle-generator': typeof ToolCircleGeneratorRoute
  '/tool/enchant-order': typeof ToolEnchantOrderRoute
  '/tool/firework-generator': typeof ToolFireworkGeneratorRoute
  '/tool/item-checklist': typeof ToolItemChecklistRoute
  '/tool/nether-portal': typeof ToolNetherPortalRoute
  '/tool/potion-maker': typeof ToolPotionMakerRoute
  '/tool/seed-map': typeof ToolSeedMapRoute
  '/tool/shield-generator': typeof ToolShieldGeneratorRoute
  '/tool/slime-chunk-finder': typeof ToolSlimeChunkFinderRoute
  '/tool/stack-calculator': typeof ToolStackCalculatorRoute
  '/tool/villager-trading': typeof ToolVillagerTradingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tool/3d-armor-trim-viewer': typeof Tool3dArmorTrimViewerRoute
  '/tool/banner-generator': typeof ToolBannerGeneratorRoute
  '/tool/best-enchantments': typeof ToolBestEnchantmentsRoute
  '/tool/circle-generator': typeof ToolCircleGeneratorRoute
  '/tool/enchant-order': typeof ToolEnchantOrderRoute
  '/tool/firework-generator': typeof ToolFireworkGeneratorRoute
  '/tool/item-checklist': typeof ToolItemChecklistRoute
  '/tool/nether-portal': typeof ToolNetherPortalRoute
  '/tool/potion-maker': typeof ToolPotionMakerRoute
  '/tool/seed-map': typeof ToolSeedMapRoute
  '/tool/shield-generator': typeof ToolShieldGeneratorRoute
  '/tool/slime-chunk-finder': typeof ToolSlimeChunkFinderRoute
  '/tool/stack-calculator': typeof ToolStackCalculatorRoute
  '/tool/villager-trading': typeof ToolVillagerTradingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tool/3d-armor-trim-viewer'
    | '/tool/banner-generator'
    | '/tool/best-enchantments'
    | '/tool/circle-generator'
    | '/tool/enchant-order'
    | '/tool/firework-generator'
    | '/tool/item-checklist'
    | '/tool/nether-portal'
    | '/tool/potion-maker'
    | '/tool/seed-map'
    | '/tool/shield-generator'
    | '/tool/slime-chunk-finder'
    | '/tool/stack-calculator'
    | '/tool/villager-trading'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tool/3d-armor-trim-viewer'
    | '/tool/banner-generator'
    | '/tool/best-enchantments'
    | '/tool/circle-generator'
    | '/tool/enchant-order'
    | '/tool/firework-generator'
    | '/tool/item-checklist'
    | '/tool/nether-portal'
    | '/tool/potion-maker'
    | '/tool/seed-map'
    | '/tool/shield-generator'
    | '/tool/slime-chunk-finder'
    | '/tool/stack-calculator'
    | '/tool/villager-trading'
  id:
    | '__root__'
    | '/'
    | '/tool/3d-armor-trim-viewer'
    | '/tool/banner-generator'
    | '/tool/best-enchantments'
    | '/tool/circle-generator'
    | '/tool/enchant-order'
    | '/tool/firework-generator'
    | '/tool/item-checklist'
    | '/tool/nether-portal'
    | '/tool/potion-maker'
    | '/tool/seed-map'
    | '/tool/shield-generator'
    | '/tool/slime-chunk-finder'
    | '/tool/stack-calculator'
    | '/tool/villager-trading'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Tool3dArmorTrimViewerRoute: typeof Tool3dArmorTrimViewerRoute
  ToolBannerGeneratorRoute: typeof ToolBannerGeneratorRoute
  ToolBestEnchantmentsRoute: typeof ToolBestEnchantmentsRoute
  ToolCircleGeneratorRoute: typeof ToolCircleGeneratorRoute
  ToolEnchantOrderRoute: typeof ToolEnchantOrderRoute
  ToolFireworkGeneratorRoute: typeof ToolFireworkGeneratorRoute
  ToolItemChecklistRoute: typeof ToolItemChecklistRoute
  ToolNetherPortalRoute: typeof ToolNetherPortalRoute
  ToolPotionMakerRoute: typeof ToolPotionMakerRoute
  ToolSeedMapRoute: typeof ToolSeedMapRoute
  ToolShieldGeneratorRoute: typeof ToolShieldGeneratorRoute
  ToolSlimeChunkFinderRoute: typeof ToolSlimeChunkFinderRoute
  ToolStackCalculatorRoute: typeof ToolStackCalculatorRoute
  ToolVillagerTradingRoute: typeof ToolVillagerTradingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/3d-armor-trim-viewer': {
      id: '/tool/3d-armor-trim-viewer'
      path: '/tool/3d-armor-trim-viewer'
      fullPath: '/tool/3d-armor-trim-viewer'
      preLoaderRoute: typeof Tool3dArmorTrimViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/banner-generator': {
      id: '/tool/banner-generator'
      path: '/tool/banner-generator'
      fullPath: '/tool/banner-generator'
      preLoaderRoute: typeof ToolBannerGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/best-enchantments': {
      id: '/tool/best-enchantments'
      path: '/tool/best-enchantments'
      fullPath: '/tool/best-enchantments'
      preLoaderRoute: typeof ToolBestEnchantmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/circle-generator': {
      id: '/tool/circle-generator'
      path: '/tool/circle-generator'
      fullPath: '/tool/circle-generator'
      preLoaderRoute: typeof ToolCircleGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/enchant-order': {
      id: '/tool/enchant-order'
      path: '/tool/enchant-order'
      fullPath: '/tool/enchant-order'
      preLoaderRoute: typeof ToolEnchantOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/firework-generator': {
      id: '/tool/firework-generator'
      path: '/tool/firework-generator'
      fullPath: '/tool/firework-generator'
      preLoaderRoute: typeof ToolFireworkGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/item-checklist': {
      id: '/tool/item-checklist'
      path: '/tool/item-checklist'
      fullPath: '/tool/item-checklist'
      preLoaderRoute: typeof ToolItemChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/nether-portal': {
      id: '/tool/nether-portal'
      path: '/tool/nether-portal'
      fullPath: '/tool/nether-portal'
      preLoaderRoute: typeof ToolNetherPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/potion-maker': {
      id: '/tool/potion-maker'
      path: '/tool/potion-maker'
      fullPath: '/tool/potion-maker'
      preLoaderRoute: typeof ToolPotionMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/seed-map': {
      id: '/tool/seed-map'
      path: '/tool/seed-map'
      fullPath: '/tool/seed-map'
      preLoaderRoute: typeof ToolSeedMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/shield-generator': {
      id: '/tool/shield-generator'
      path: '/tool/shield-generator'
      fullPath: '/tool/shield-generator'
      preLoaderRoute: typeof ToolShieldGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/slime-chunk-finder': {
      id: '/tool/slime-chunk-finder'
      path: '/tool/slime-chunk-finder'
      fullPath: '/tool/slime-chunk-finder'
      preLoaderRoute: typeof ToolSlimeChunkFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/stack-calculator': {
      id: '/tool/stack-calculator'
      path: '/tool/stack-calculator'
      fullPath: '/tool/stack-calculator'
      preLoaderRoute: typeof ToolStackCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/villager-trading': {
      id: '/tool/villager-trading'
      path: '/tool/villager-trading'
      fullPath: '/tool/villager-trading'
      preLoaderRoute: typeof ToolVillagerTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Tool3dArmorTrimViewerRoute: Tool3dArmorTrimViewerRoute,
  ToolBannerGeneratorRoute: ToolBannerGeneratorRoute,
  ToolBestEnchantmentsRoute: ToolBestEnchantmentsRoute,
  ToolCircleGeneratorRoute: ToolCircleGeneratorRoute,
  ToolEnchantOrderRoute: ToolEnchantOrderRoute,
  ToolFireworkGeneratorRoute: ToolFireworkGeneratorRoute,
  ToolItemChecklistRoute: ToolItemChecklistRoute,
  ToolNetherPortalRoute: ToolNetherPortalRoute,
  ToolPotionMakerRoute: ToolPotionMakerRoute,
  ToolSeedMapRoute: ToolSeedMapRoute,
  ToolShieldGeneratorRoute: ToolShieldGeneratorRoute,
  ToolSlimeChunkFinderRoute: ToolSlimeChunkFinderRoute,
  ToolStackCalculatorRoute: ToolStackCalculatorRoute,
  ToolVillagerTradingRoute: ToolVillagerTradingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
