/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Tool3dArmorTrimViewerRouteImport } from './routes/tool/3d-armor-trim-viewer'
import { Route as ToolBannerCraftingRouteImport } from './routes/tool/banner-crafting'
import { Route as ToolBestEnchantmentsRouteImport } from './routes/tool/best-enchantments'
import { Route as ToolFireworkCraftingRouteImport } from './routes/tool/firework-crafting'
import { Route as ToolItemChecklistRouteImport } from './routes/tool/item-checklist'
import { Route as ToolPotionMakerRouteImport } from './routes/tool/potion-maker'
import { Route as ToolSeedMapRouteImport } from './routes/tool/seed-map'
import { Route as ToolShieldDesignerRouteImport } from './routes/tool/shield-designer'
import { Route as ToolStackCalculatorRouteImport } from './routes/tool/stack-calculator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Tool3dArmorTrimViewerRoute = Tool3dArmorTrimViewerRouteImport.update({
  id: '/tool/3d-armor-trim-viewer',
  path: '/tool/3d-armor-trim-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolBannerCraftingRoute = ToolBannerCraftingRouteImport.update({
  id: '/tool/banner-crafting',
  path: '/tool/banner-crafting',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolBestEnchantmentsRoute = ToolBestEnchantmentsRouteImport.update({
  id: '/tool/best-enchantments',
  path: '/tool/best-enchantments',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolFireworkCraftingRoute = ToolFireworkCraftingRouteImport.update({
  id: '/tool/firework-crafting',
  path: '/tool/firework-crafting',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolItemChecklistRoute = ToolItemChecklistRouteImport.update({
  id: '/tool/item-checklist',
  path: '/tool/item-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolPotionMakerRoute = ToolPotionMakerRouteImport.update({
  id: '/tool/potion-maker',
  path: '/tool/potion-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolSeedMapRoute = ToolSeedMapRouteImport.update({
  id: '/tool/seed-map',
  path: '/tool/seed-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolShieldDesignerRoute = ToolShieldDesignerRouteImport.update({
  id: '/tool/shield-designer',
  path: '/tool/shield-designer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolStackCalculatorRoute = ToolStackCalculatorRouteImport.update({
  id: '/tool/stack-calculator',
  path: '/tool/stack-calculator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tool/3d-armor-trim-viewer': typeof Tool3dArmorTrimViewerRoute
  '/tool/banner-crafting': typeof ToolBannerCraftingRoute
  '/tool/best-enchantments': typeof ToolBestEnchantmentsRoute
  '/tool/firework-crafting': typeof ToolFireworkCraftingRoute
  '/tool/item-checklist': typeof ToolItemChecklistRoute
  '/tool/potion-maker': typeof ToolPotionMakerRoute
  '/tool/seed-map': typeof ToolSeedMapRoute
  '/tool/shield-designer': typeof ToolShieldDesignerRoute
  '/tool/stack-calculator': typeof ToolStackCalculatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tool/3d-armor-trim-viewer': typeof Tool3dArmorTrimViewerRoute
  '/tool/banner-crafting': typeof ToolBannerCraftingRoute
  '/tool/best-enchantments': typeof ToolBestEnchantmentsRoute
  '/tool/firework-crafting': typeof ToolFireworkCraftingRoute
  '/tool/item-checklist': typeof ToolItemChecklistRoute
  '/tool/potion-maker': typeof ToolPotionMakerRoute
  '/tool/seed-map': typeof ToolSeedMapRoute
  '/tool/shield-designer': typeof ToolShieldDesignerRoute
  '/tool/stack-calculator': typeof ToolStackCalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tool/3d-armor-trim-viewer': typeof Tool3dArmorTrimViewerRoute
  '/tool/banner-crafting': typeof ToolBannerCraftingRoute
  '/tool/best-enchantments': typeof ToolBestEnchantmentsRoute
  '/tool/firework-crafting': typeof ToolFireworkCraftingRoute
  '/tool/item-checklist': typeof ToolItemChecklistRoute
  '/tool/potion-maker': typeof ToolPotionMakerRoute
  '/tool/seed-map': typeof ToolSeedMapRoute
  '/tool/shield-designer': typeof ToolShieldDesignerRoute
  '/tool/stack-calculator': typeof ToolStackCalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tool/3d-armor-trim-viewer'
    | '/tool/banner-crafting'
    | '/tool/best-enchantments'
    | '/tool/firework-crafting'
    | '/tool/item-checklist'
    | '/tool/potion-maker'
    | '/tool/seed-map'
    | '/tool/shield-designer'
    | '/tool/stack-calculator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tool/3d-armor-trim-viewer'
    | '/tool/banner-crafting'
    | '/tool/best-enchantments'
    | '/tool/firework-crafting'
    | '/tool/item-checklist'
    | '/tool/potion-maker'
    | '/tool/seed-map'
    | '/tool/shield-designer'
    | '/tool/stack-calculator'
  id:
    | '__root__'
    | '/'
    | '/tool/3d-armor-trim-viewer'
    | '/tool/banner-crafting'
    | '/tool/best-enchantments'
    | '/tool/firework-crafting'
    | '/tool/item-checklist'
    | '/tool/potion-maker'
    | '/tool/seed-map'
    | '/tool/shield-designer'
    | '/tool/stack-calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Tool3dArmorTrimViewerRoute: typeof Tool3dArmorTrimViewerRoute
  ToolBannerCraftingRoute: typeof ToolBannerCraftingRoute
  ToolBestEnchantmentsRoute: typeof ToolBestEnchantmentsRoute
  ToolFireworkCraftingRoute: typeof ToolFireworkCraftingRoute
  ToolItemChecklistRoute: typeof ToolItemChecklistRoute
  ToolPotionMakerRoute: typeof ToolPotionMakerRoute
  ToolSeedMapRoute: typeof ToolSeedMapRoute
  ToolShieldDesignerRoute: typeof ToolShieldDesignerRoute
  ToolStackCalculatorRoute: typeof ToolStackCalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/3d-armor-trim-viewer': {
      id: '/tool/3d-armor-trim-viewer'
      path: '/tool/3d-armor-trim-viewer'
      fullPath: '/tool/3d-armor-trim-viewer'
      preLoaderRoute: typeof Tool3dArmorTrimViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/banner-crafting': {
      id: '/tool/banner-crafting'
      path: '/tool/banner-crafting'
      fullPath: '/tool/banner-crafting'
      preLoaderRoute: typeof ToolBannerCraftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/best-enchantments': {
      id: '/tool/best-enchantments'
      path: '/tool/best-enchantments'
      fullPath: '/tool/best-enchantments'
      preLoaderRoute: typeof ToolBestEnchantmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/firework-crafting': {
      id: '/tool/firework-crafting'
      path: '/tool/firework-crafting'
      fullPath: '/tool/firework-crafting'
      preLoaderRoute: typeof ToolFireworkCraftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/item-checklist': {
      id: '/tool/item-checklist'
      path: '/tool/item-checklist'
      fullPath: '/tool/item-checklist'
      preLoaderRoute: typeof ToolItemChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/potion-maker': {
      id: '/tool/potion-maker'
      path: '/tool/potion-maker'
      fullPath: '/tool/potion-maker'
      preLoaderRoute: typeof ToolPotionMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/seed-map': {
      id: '/tool/seed-map'
      path: '/tool/seed-map'
      fullPath: '/tool/seed-map'
      preLoaderRoute: typeof ToolSeedMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/shield-designer': {
      id: '/tool/shield-designer'
      path: '/tool/shield-designer'
      fullPath: '/tool/shield-designer'
      preLoaderRoute: typeof ToolShieldDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/stack-calculator': {
      id: '/tool/stack-calculator'
      path: '/tool/stack-calculator'
      fullPath: '/tool/stack-calculator'
      preLoaderRoute: typeof ToolStackCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Tool3dArmorTrimViewerRoute: Tool3dArmorTrimViewerRoute,
  ToolBannerCraftingRoute: ToolBannerCraftingRoute,
  ToolBestEnchantmentsRoute: ToolBestEnchantmentsRoute,
  ToolFireworkCraftingRoute: ToolFireworkCraftingRoute,
  ToolItemChecklistRoute: ToolItemChecklistRoute,
  ToolPotionMakerRoute: ToolPotionMakerRoute,
  ToolSeedMapRoute: ToolSeedMapRoute,
  ToolShieldDesignerRoute: ToolShieldDesignerRoute,
  ToolStackCalculatorRoute: ToolStackCalculatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
