/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Tool3dArmorTrimViewerRouteImport } from './routes/tool/3d-armor-trim-viewer'
import { Route as ToolItemChecklistRouteImport } from './routes/tool/item-checklist'
import { Route as ToolStackCalculatorRouteImport } from './routes/tool/stack-calculator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Tool3dArmorTrimViewerRoute = Tool3dArmorTrimViewerRouteImport.update({
  id: '/tool/3d-armor-trim-viewer',
  path: '/tool/3d-armor-trim-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolItemChecklistRoute = ToolItemChecklistRouteImport.update({
  id: '/tool/item-checklist',
  path: '/tool/item-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolStackCalculatorRoute = ToolStackCalculatorRouteImport.update({
  id: '/tool/stack-calculator',
  path: '/tool/stack-calculator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tool/3d-armor-trim-viewer': typeof Tool3dArmorTrimViewerRoute
  '/tool/item-checklist': typeof ToolItemChecklistRoute
  '/tool/stack-calculator': typeof ToolStackCalculatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tool/3d-armor-trim-viewer': typeof Tool3dArmorTrimViewerRoute
  '/tool/item-checklist': typeof ToolItemChecklistRoute
  '/tool/stack-calculator': typeof ToolStackCalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tool/3d-armor-trim-viewer': typeof Tool3dArmorTrimViewerRoute
  '/tool/item-checklist': typeof ToolItemChecklistRoute
  '/tool/stack-calculator': typeof ToolStackCalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tool/3d-armor-trim-viewer'
    | '/tool/item-checklist'
    | '/tool/stack-calculator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tool/3d-armor-trim-viewer'
    | '/tool/item-checklist'
    | '/tool/stack-calculator'
  id:
    | '__root__'
    | '/'
    | '/tool/3d-armor-trim-viewer'
    | '/tool/item-checklist'
    | '/tool/stack-calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Tool3dArmorTrimViewerRoute: typeof Tool3dArmorTrimViewerRoute
  ToolItemChecklistRoute: typeof ToolItemChecklistRoute
  ToolStackCalculatorRoute: typeof ToolStackCalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/3d-armor-trim-viewer': {
      id: '/tool/3d-armor-trim-viewer'
      path: '/tool/3d-armor-trim-viewer'
      fullPath: '/tool/3d-armor-trim-viewer'
      preLoaderRoute: typeof Tool3dArmorTrimViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/item-checklist': {
      id: '/tool/item-checklist'
      path: '/tool/item-checklist'
      fullPath: '/tool/item-checklist'
      preLoaderRoute: typeof ToolItemChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/stack-calculator': {
      id: '/tool/stack-calculator'
      path: '/tool/stack-calculator'
      fullPath: '/tool/stack-calculator'
      preLoaderRoute: typeof ToolStackCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Tool3dArmorTrimViewerRoute: Tool3dArmorTrimViewerRoute,
  ToolItemChecklistRoute: ToolItemChecklistRoute,
  ToolStackCalculatorRoute: ToolStackCalculatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
